### PR TITLE
Fix i18n issues

### LINKED ISSUE #294: i18n - Some strings aren't translatable and others need small fixes
### Describe the bug

Some translation strings don't have textdomain, some have the wrong textdomain and others have no comment to translators.

### Steps to Reproduce

1. Set WP to a language that the plugin has the full translation
2. Go to Settings > Discussion
3. See some strings untranslated

### Screenshots, screen recording, code snippet

imagem

### Environment information

_No response_

### WordPress information

WP 6.6.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pedro-mendonca**
### Description of the Change

- [x] Fix wrong textdomains
- [x] Add missing textdomains
- [x] Add missing comment to translators in string with placeholder
- [x] Fix some simple coding standard issues

Please see issue #294 for a full issue description and screenshots.

Closes #294 

### How to test the Change
Install a language that the plugin is 100% translated
Go to Settings > Discussion and see all the plugin related strings translated.

### Changelog Entry

Fixed - I18n issues

### Credits

Props @pedro-mendonca

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]
@pedro-mendonca Thanks for the PR, this looks and tests great!

**Comment by faisal-alvi** [comment]
@dkotter We've removed the text domain from `avatar_ratings` in #175 to fix issues #88 and #157. This PR adds them back, so we should've verified that it doesn't cause the issues to reoccur.

**Comment by pedro-mendonca** [comment]
@faisal-alvi if the site language is set to Language A, and user-language is set to Language B, all these strings are presented in Language B.
The strings appear in the translation table on w.org, so they should be loaded from the .po file and not from core.

**Comment by dkotter** [comment]
> @dkotter We've removed the text domain from `avatar_ratings` in #175 to fix issues #88 and #157. This PR adds them back, so we should've verified that it doesn't cause the issues to reoccur.

That's a good callout and is something I tested. I see the proper translations both if a site language is set and if a user language is set when testing this PR. Not sure if there are other changes we've made that helped fix this since the original issue was reported but I'm not seeing any regression, though feel free to test yourself to ensure that is the case

**Pull request merged**
