### PR TITLE
Introducing Package file

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Description of the Change

The package file is introduced.

### Benefits

Helpful in cases where a new `script` is required like https://github.com/10up/simple-local-avatars/pull/85#issuecomment-1000456744. Added `uglifyjs` script to overcome the mentioned issue.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jeffpaul — CHANGES_REQUESTED** [review]
@faisal-alvi you'll want to add those files to https://github.com/10up/simple-local-avatars/blob/develop/.gitattributes so that they don't end up in the released version.

**Comment by claytoncollie** [comment]
@faisal-alvi A minor suggestion, but renaming `uglifyjs` to `build` would be a better name to build the assets.

**Comment by faisal-alvi** [comment]
@claytoncollie Thanks for the suggestion, I had preserved the “build” for the actual building of the “whole project” whereas the `uglifyjs` is minimizing only one JS file. But as we do not have any other files to be built (for now), we can utilize the word “build”.

**Comment by jeffpaul** [comment]
Odd that the previous commit passed checks but the latest failed.  Given that its WP Acceptance (and that we should be setting up Cypress e2e tests here anyway) I think I'm fine with this for now (ideally we get those e2e tests in place before the next release).

**Review by cadic — APPROVED** [review]

**Pull request merged**
