### PR TITLE
Release/2.2.0

### LINKED ISSUE #56: Test against WordPress 5.5
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.5 is released, we'll want to test Simple Local Avatars to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Simple Local Avatars on WordPress 5.5
- [ ] open issues for any incompatibilities noted in testing
- [x] resolve issues identified in testing
- [x] bump "tested up to" version
- [x] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
WordPress 5.4 testing issue --> https://github.com/10up/simple-local-avatars/issues/42

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change

Release and version bump to 2.2.0.

### Alternate Designs

none.

### Benefits

Properly updates plugin version number to alert consumers to `all the wonderful new things`.

### Possible Drawbacks

none identified.

### Verification Process

Verified manually via the GitHub Desktop UI.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Relates to #51.  Relates to https://github.com/10up/Open-Source-Best-Practices/issues/62.

### Changelog Entry

```
### Changed
- New plugin banner and icon (props @JackieKjome)
```

### CODE REVIEW

**Comment by helen** [comment]
This appears to need a refresh but otherwise looks fine to me.

**Comment by danielpost** [comment]
Is there an idea of when this will be released? Would be great to be able to use `get_avatar_url` instead!

**Comment by helen** [comment]
@danielpost I lost track of this because honestly I thought we had already released it 🤦‍♀️ We try not to do Friday releases on the off chance that something urgent needs to be fixed, so I'll make a note to try to get it done Monday.

**Comment by danielpost** [comment]
@helen Amazing, thanks so much!

**Pull request merged**
