### PR TITLE
update wp tested-up-to 5.3 in readme.txt

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change

Mimics #36 to the `master` branch to trigger the GitHub Action.

### Alternate Designs

none

### Benefits

Ensures the plugin bump deploys to .ORG.

### Possible Drawbacks

none identified.

### Verification Process

Manually verified via the GitHub web UI.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/10up/simple-local-avatars/blob/develop/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Relates to #35

### CODE REVIEW

**Comment by jeffpaul** [comment]
Huh, don't know why the GitHub Action didn't pick this up and update .ORG.  Will have to investigate what's going on there.

**Comment by dinhtungdu** [comment]
It's the current limitation, see https://github.com/10up/action-wordpress-plugin-asset-update#known-issues

> So far in testing it is possible to limit it to pushes that include readme/asset files as specified, but not ones that only include those files.

**Comment by dinhtungdu** [comment]
@jeffpaul, you need to merge new commits from `develop` to `master` to get the action triggered for the current configuration.
```
name: Plugin asset/readme update
on:
  push:
    branches:
    - master
```

**Comment by jeffpaul** [comment]
Nice catch @dinhtungdu, looks like there's a small update in the main plugin file so we'll get those changes into master in our next release version (likely one targeting the work from #40).

**Pull request merged**
