### PR TITLE
Bumping tested up to version.

### PR DESCRIPTION
**Pull request by ghost**
Bumping WP tested up to version to 5.4. I followed [the same verification process as here.](https://github.com/10up/simple-local-avatars/pull/36)

For #42

### CODE REVIEW

**Comment by jeffpaul** [comment]
@helen we'll need to update this to merge into `master` to trigger the GitHub Action, yeah?

**Comment by jeffpaul** [comment]
I went ahead and pushed the same change to `master` to trigger the readme/asset action, but nothing happened.  Turns out our actions in `master` are the old format and won't work.  Sigh, we'll have to wait for a release here to get things back in order on `master`.

**Comment by helen** [comment]
@jeffpaul Should be okay to update the workflow file in master and it'll run when merging that :)

**Comment by jeffpaul** [comment]
Thanks @helen that worked (see #44) though the odd thing is dotorg now shows tested-up-to 5.4.1 but our readme.txt shows 5.4. Not a major issue, just not sure how that discrepancy snuck in.

**Comment by helen** [comment]
@jeffpaul .org only requires that we bump majors :)

**Comment by jeffpaul** [comment]
@helen I'm aware of that, my head-scratcher was that our readme.txt states 5.4 while the plugin page on dotorg shows 5.4.1.  I'm not certain how dotorg inferred 5.4.1 from our stated 5.4?

**Comment by helen** [comment]
@jeffpaul Right, we only bump majors, and .org assumes/displays the latest minor in that major branch

**Comment by jeffpaul** [comment]
Huh, ok.  That's a bit odd and potentially concerning as theoretically there could be an conflict between a plugin and a WP minor, especially now that [minor releases can include enhancements](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-minor-versions/), that would only be caught in specific testing against a minor versus against a major release.

**Pull request merged**
